site_name: notes

docs_dir: Academics

extra_css:
  - style.css

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

nav:
  - Home: 'index.md'
  - Course List: 'Course%20List.md'
  - Fall 2022:
    - LIN 1Y: "/FQ%20'22/LIN%201Y.md"
    - PHY 9D: "/FQ%20'22/PHY%209D.md"
    - PHY 9HA: "/FQ%20'22/PHY%209HA.md"
    - PHY 40: "/FQ%20'22/PHY%2040.md"
    - PHY 104A: "/FQ%20'22/PHY%20104A.md"
    - PHY 116A: "/FQ%20'22/PHY%20116A.md"
  - Winter 2023: "/WQ%20'22/"
    - LIN 103B: "/WQ%20'23/LIN%20103B.md"
    - MAT 108: "/WQ%20'23/MAT%20108.md"
    - MAT 119A: "/WQ%20'23/MAT%20119A.md"
    - PHY 45: "/WQ%20'23/PHY%2045.md"
    - PHY 80: "/WQ%20'23/PHY%2080.md"
    - PHY 105A: "/WQ%20'22/PHY%20105A.md"
    - PHY 110A: "/WQ%20'22/PHY%20110A.md"
    - PHY 116B: "/WQ%20'22/PHY%20116B.md"
  - Spring 2023: "/SQ%20'22/"
    - LIN 165: "/SQ%20'23/LIN%20165.md"
    - MAT 127A: "/SQ%20'23/MAT%20127A.md"
    - MAT 128B: "/SQ%20'23/MAT%20128B.md"
    - MAT 135A: "/SQ%20'23/MAT%20135A.md"
    - PHY 105B: "/SQ%20'22/PHY%20105B.md"
    - PHY 108: "/SQ%20'22/PHY%20108.md"
    - PHY 110B: "/SQ%20'22/PHY%20110B.md"
  - Summer 2023: "/MQ%20'22/"
    - MAT 127B: "/MQ%20'23/MAT%20127B.md"
    - MAT 128A: "/MQ%20'23/MAT%20128A.md"
  - Fall 2023: "/FQ%20'23/"
    - LIN 112: "/FQ%20'23/LIN%20112.md"
    - LIN 141: "/FQ%20'23/LIN%20141.md"
    - MAT 150A: "/FQ%20'23/MAT%20150A.md"
    - MAT 168: "/FQ%20'23/MAT%20168.md"
    - MAT 185A: "/FQ%20'23/MAT%20185A.md"
    - PHY 105C: "/FQ%20'22/PHY%20105C.md"
    - PHY 112: "/FQ%20'22/PHY%20112.md"
    - PHY 115A: "/FQ%20'22/PHY%20115A.md"

not_in_nav: |
  Notes/*