site_name: notes

docs_dir: Academics

extra_css:
  - style.css

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

nav:
  - Home: 'index/'
  - Course List: 'Course%20List/'
  - Fall 2022:
    - LIN 1Y: "/FQ%20'22/LIN%201Y/"
    - PHY 9D: "/FQ%20'22/PHY%209D/"
    - PHY 9HA: "/FQ%20'22/PHY%209HA/"
    - PHY 40: "/FQ%20'22/PHY%2040/"
    - PHY 104A: "/FQ%20'22/PHY%20104A/"
    - PHY 116A: "/FQ%20'22/PHY%20116A/"
  - Winter 2023:
    - LIN 103B: "/WQ%20'23/LIN%20103B/"
    - MAT 108: "/WQ%20'23/MAT%20108/"
    - MAT 119A: "/WQ%20'23/MAT%20119A/"
    - PHY 45: "/WQ%20'23/PHY%2045/"
    - PHY 80: "/WQ%20'23/PHY%2080/"
    - PHY 105A: "/WQ%20'22/PHY%20105A/"
    - PHY 110A: "/WQ%20'22/PHY%20110A/"
    - PHY 116B: "/WQ%20'22/PHY%20116B/"
  - Spring 2023:
    - LIN 165: "/SQ%20'23/LIN%20165/"
    - MAT 127A: "/SQ%20'23/MAT%20127A/"
    - MAT 128B: "/SQ%20'23/MAT%20128B/"
    - MAT 135A: "/SQ%20'23/MAT%20135A/"
    - PHY 105B: "/SQ%20'22/PHY%20105B/"
    - PHY 108: "/SQ%20'22/PHY%20108/"
    - PHY 110B: "/SQ%20'22/PHY%20110B/"
  - Summer 2023:
    - MAT 127B: "/MQ%20'23/MAT%20127B/"
    - MAT 128A: "/MQ%20'23/MAT%20128A/"
  - Fall 2023:
    - LIN 112: "/FQ%20'23/LIN%20112/"
    - LIN 141: "/FQ%20'23/LIN%20141/"
    - MAT 150A: "/FQ%20'23/MAT%20150A/"
    - MAT 168: "/FQ%20'23/MAT%20168/"
    - MAT 185A: "/FQ%20'23/MAT%20185A/"
    - PHY 105C: "/FQ%20'22/PHY%20105C/"
    - PHY 112: "/FQ%20'22/PHY%20112/"
    - PHY 115A: "/FQ%20'22/PHY%20115A/"

not_in_nav: |
  Notes/*