site_name: notes

docs_dir: academics

extra_css:
  - style.css

theme:
    name: 'terminal'
    palette: dark

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

nav:
  - Home: './'
  - Course List: 'Course%20List/'
  - Fall 2022:
    - LIN 1Y: "./f22/LIN%201Y/"
    - PHY 9D: "./f22/PHY%209D/"
    - PHY 9HA: "./f22/PHY%209HA/"
    - PHY 40: "./f22/PHY%2040/"
    - PHY 104A: "./f22/PHY%20104A/"
    - PHY 116A: "./f22/PHY%20116A/"
  - Winter 2023:
    - LIN 103B: "./w23/LIN%20103B/"
    - MAT 108: "./w23/MAT%20108/"
    - MAT 119A: "./w23/MAT%20119A/"
    - PHY 45: "./w23/PHY%2045/"
    - PHY 80: "./w23/PHY%2080/"
    - PHY 105A: "./w23/PHY%20105A/"
    - PHY 110A: "./w23/PHY%20110A/"
    - PHY 116B: "./w23/PHY%20116B/"
  - Spring 2023:
    - LIN 165: "./s23/LIN%20165/"
    - MAT 127A: "./s23/MAT%20127A/"
    - MAT 128B: "./s23/MAT%20128B/"
    - MAT 135A: "./s23/MAT%20135A/"
    - PHY 105B: "./s23/PHY%20105B/"
    - PHY 108(L): "./s23/PHY%20108/"
    - PHY 110B: "./s23/PHY%20110B/"
  - Summer 2023:
    - MAT 127B: "./m23/MAT%20127B/"
    - MAT 128A: "./m23/MAT%20128A/"
  - Fall 2023:
    - LIN 112: "./f23/LIN%20112/"
    - LIN 141: "./f23/LIN%20141/"
    - MAT 150A: "./f23/MAT%20150A/"
    - MAT 168: "./f23/MAT%20168/"
    - MAT 185A: "./f23/MAT%20185A/"
    - PHY 105C: "./f23/PHY%20105C/"
    - PHY 112(L): "./f23/PHY%20112/"
    - PHY 115A: "./f23/PHY%20115A/"

not_in_nav: |
  Notes/*