site_name: notes

site_url: https://ravidosa.github.io/notes/

docs_dir: academics

extra_css:
  - style.css

theme:
    name: 'terminal'
    palette: dark

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      toc_depth: 2
      permalink: true

plugins:
  - search
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

nav:
  - Home: './'
  - Course List: './course-list/'
  - Library: './library/'
  - Fall 2022:
    - LIN 1Y: "./f22/lin1y/"
    - PHY 9D: "./f22/phy9d/"
    - PHY 9HA: "./f22/phy9ha/"
    - PHY 40: "./f22/phy40/"
    - PHY 104A: "./f22/phy104a/"
    - PHY 116A: "./f22/phy116a/"
  - Winter 2023:
    - LIN 103B: "./w23/lin103b/"
    - MAT 108: "./w23/mat108/"
    - MAT 119A: "./w23/mat119a/"
    - PHY 45: "./w23/phy45/"
    - PHY 80: "./w23/phy80/"
    - PHY 105A: "./w23/phy105a/"
    - PHY 110A: "./w23/phy110a/"
    - PHY 116B: "./w23/phy116b/"
  - Spring 2023:
    - LIN 165: "./s23/lin165/"
    - MAT 127A: "./s23/mat127a/"
    - MAT 128B: "./s23/mat128b/"
    - MAT 135A: "./s23/mat135a/"
    - PHY 105B: "./s23/phy105b/"
    - PHY 108: "./s23/phy108/"
    - PHY 108L: "./s23/phy108/"
    - PHY 110B: "./s23/phy110b/"
  - Summer 2023:
    - MAT 127B: "./m23/mat127b/"
    - MAT 128A: "./m23/mat128a/"
  - Fall 2023:
    - LIN 112: "./f23/lin112/"
    - LIN 141: "./f23/lin141/"
    - MAT 150A: "./f23/mat150a/"
    - MAT 168: "./f23/mat168/"
    - MAT 185A: "./f23/mat185a/"
    - PHY 105C: "./f23/phy105c/"
    - PHY 112: "./f23/phy112/"
    - PHY 112L: "./f23/phy112/"
    - PHY 115A: "./f23/phy115a/"
  - Winter 2024:
    - ECS 120: "./w24/ecs120/"
    - LIN 103A: "./w24/lin103a/"
    - LIN 131: "./w24/lin131/"
    - LIN 152: "./w24/lin152/"
    - MAT 148: "./w24/mat148/"
    - MAT 150B: "./w24/mat150b/"
    - MAT 167: "./w24/mat167/"
    - PHY 115B: "./w24/phy115b/"
    - PHY 115L: "./w24/phy115b/"
    - PHY 130A: "./w24/phy130a/"
  - Spring 2024:
    - ECS 36C: "./s24/ecs36c/"
    - ECS 127: "./s24/ecs127/"
    - MAT 127C: "./s24/mat127c/"
    - MAT 128C: "./s24/mat128c/"
    - MAT 185B: "./s24/mat185b/"
    - PHY 110L: "./s23/phy110b/"
    - PHY 122B: "./s24/phy122b/"
    - PHY 129A: "./s24/phy129a/"
    - PHY 130B: "./s24/phy130b/"

not_in_nav: |
  Notes/*
